### ISSUE TITLE
check_spatial_attribs()

### ISSUE THREAD

**Issue by toledobastos** [diptosarkar/SpatNet#1]
It seems the function check_spatial_attribs() is not an exported object from 'namespace:SpatNet'. This seems to break the function check_spatial_clustering().

**Comment by diptosarkar** [comment]
Thanks for bringing this to my notice.

I will rectify it soon.

Thanks and regards
Dipto
________________________________

**Comment by diptosarkar** [comment]
This issue is now resolved with the new version
